name: Android Main CI

on:
  push:
    branches:
      - 'master'
      - 'release/*'

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 11
      - name: Check formatting using spotless
        run: ./gradlew spotlessCheck
      - name: Build with Gradle
        run: |
          ./gradlew assembledebug
        env:
          TZ: UTC
      - name: Run test cases
        run: ./gradlew jacocoTestPlayDebugUnitTestReport
        env:
          TZ: UTC
      - name: Publish test cases
        run: |
          export CODACY_PROJECT_TOKEN=${{ secrets.CODACY_TOKEN }}
          bash <(curl -Ls https://coverage.codacy.com/get.sh)
