name: Android Feature CI

on:
  pull_request:
    branches:
      - 'master'
      - 'release/*'
      - 'hotfix/*'

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 11
      - name: Check formatting using spotless
        run: ./gradlew spotlessCheck --stacktrace
      - name: Build with Gradle
        run: |
          ./gradlew assembledebug --stacktrace
        env:
          TZ: UTC
      - name: Run test cases
        run: ./gradlew jacocoTestPlayDebugUnitTestReport --stacktrace --info
        env:
          TZ: UTC